"""BMI"""
def main():
    """BMI"""
    name1 = input()
    weight1 = float(input())
    tall1 = float(input())
    name2 = input()
    weight2 = float(input())
    tall2 = float(input())
    name3 = input()
    weight3 = float(input())
    tall3 = float(input())
    name4 = input()
    weight4 = float(input())
    tall4 = float(input())
    name5 = input()
    weight5 = float(input())
    tall5 = float(input())
    print(name1 + "'s  BMI =", "%.2f" % (weight1 / ((tall1/100)**2)))
    print(name2 + "'s  BMI =", "%.2f" % (weight2 / ((tall2 / 100) ** 2)))
    print(name3 + "'s  BMI =", "%.2f" % (weight3 / ((tall3 / 100) ** 2)))
    print(name4 + "'s  BMI =", "%.2f" % (weight4 / ((tall4 / 100) ** 2)))
    print(name5 + "'s  BMI =", "%.2f" % (weight5 / ((tall5 / 100) ** 2)))
main()
